package com.android.angelslike.bean.dbbean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_BEAN.
 */
public class UserBean extends com.hzf.bean.BaseBean  {

    private long id;
    /** Not-null value. */
    private String phone = "";
    /** Not-null value. */
    private String unionid = "";
    /** Not-null value. */
    private String img = "";
    private long userid;
    private long mregistrationtime;
    private long sex;
    /** Not-null value. */
    private String loginkey = "";
    /** Not-null value. */
    private String logins = "";
    /** Not-null value. */
    private String city = "";
    /** Not-null value. */
    private String mfen = "";
    /** Not-null value. */
    private String address = "";
    /** Not-null value. */
    private String dis = "";
    /** Not-null value. */
    private String name = "";
    /** Not-null value. */
    private String yanvalue = "";
    /** Not-null value. */
    private String money = "";
    /** Not-null value. */
    private String pro = "";
    /** Not-null value. */
    private String fen = "";
    /** Not-null value. */
    private String openid = "";
    /** Not-null value. */
    private String user = "";
    /** Not-null value. */
    private String qq = "";
    /** Not-null value. */
    private String isadmin = "";

    public UserBean() {
    }

    public UserBean(long id, String phone, String unionid, String img, long userid, long mregistrationtime, long sex, String loginkey, String logins, String city, String mfen, String address, String dis, String name, String yanvalue, String money, String pro, String fen, String openid, String user, String qq, String isadmin) {
        this.id = id;
        this.phone = phone;
        this.unionid = unionid;
        this.img = img;
        this.userid = userid;
        this.mregistrationtime = mregistrationtime;
        this.sex = sex;
        this.loginkey = loginkey;
        this.logins = logins;
        this.city = city;
        this.mfen = mfen;
        this.address = address;
        this.dis = dis;
        this.name = name;
        this.yanvalue = yanvalue;
        this.money = money;
        this.pro = pro;
        this.fen = fen;
        this.openid = openid;
        this.user = user;
        this.qq = qq;
        this.isadmin = isadmin;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getUnionid() {
        return unionid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    /** Not-null value. */
    public String getImg() {
        return img;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImg(String img) {
        this.img = img;
    }

    public long getUserid() {
        return userid;
    }

    public void setUserid(long userid) {
        this.userid = userid;
    }

    public long getMregistrationtime() {
        return mregistrationtime;
    }

    public void setMregistrationtime(long mregistrationtime) {
        this.mregistrationtime = mregistrationtime;
    }

    public long getSex() {
        return sex;
    }

    public void setSex(long sex) {
        this.sex = sex;
    }

    /** Not-null value. */
    public String getLoginkey() {
        return loginkey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginkey(String loginkey) {
        this.loginkey = loginkey;
    }

    /** Not-null value. */
    public String getLogins() {
        return logins;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogins(String logins) {
        this.logins = logins;
    }

    /** Not-null value. */
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }

    /** Not-null value. */
    public String getMfen() {
        return mfen;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMfen(String mfen) {
        this.mfen = mfen;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getDis() {
        return dis;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDis(String dis) {
        this.dis = dis;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getYanvalue() {
        return yanvalue;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setYanvalue(String yanvalue) {
        this.yanvalue = yanvalue;
    }

    /** Not-null value. */
    public String getMoney() {
        return money;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMoney(String money) {
        this.money = money;
    }

    /** Not-null value. */
    public String getPro() {
        return pro;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPro(String pro) {
        this.pro = pro;
    }

    /** Not-null value. */
    public String getFen() {
        return fen;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFen(String fen) {
        this.fen = fen;
    }

    /** Not-null value. */
    public String getOpenid() {
        return openid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /** Not-null value. */
    public String getUser() {
        return user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser(String user) {
        this.user = user;
    }

    /** Not-null value. */
    public String getQq() {
        return qq;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /** Not-null value. */
    public String getIsadmin() {
        return isadmin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIsadmin(String isadmin) {
        this.isadmin = isadmin;
    }

}
